Repository openthread/ot-br-posix, pull requests merged in 2018-09, with the labels that each got.

#165 [commissioner] clean up and enhance commissioner
  src/common/tlv.hpp
  src/utils/steeringdata.hpp
  tests/meshcop/Makefile.am
  tests/meshcop/addr_utils.cpp
  tests/meshcop/addr_utils.hpp
  tests/meshcop/commissioner.cpp
  tests/meshcop/commissioner.hpp
  tests/meshcop/commissioner_argcargv.cpp
  tests/meshcop/commissioner_argcargv.hpp
  tests/meshcop/commissioner_compute.cpp
  tests/meshcop/commissioner_constants.hpp
  tests/meshcop/commissioner_selftest.cpp
  tests/meshcop/commissioner_utils.hpp
  tests/meshcop/device_hash.cpp
  tests/meshcop/device_hash.hpp
  tests/meshcop/joiner_session.cpp
  tests/meshcop/joiner_session.hpp
  tests/meshcop/main.cpp
Labels: P2, bug, cla: yes, enhancement

#185 [travis] update configure options
  .travis/before_install.sh
  tests/meshcop/meshcop
Labels: P2, cla: yes

#177 [nat64] fix tayga start
  .travis/before_install.sh
  .travis/script.sh
  script/_nat64
Labels: P3, bug, cla: yes

#186 [meshcop] allow commissioner to set joiner filter in separate method
  tests/meshcop/commissioner.cpp
  tests/meshcop/commissioner.hpp
  tests/meshcop/main.cpp
Labels: cla: yes

#190 [commissioner] quick fix for ip6 support
  tests/meshcop/commissioner.cpp
  tests/meshcop/commissioner.hpp
  tests/meshcop/commissioner_argcargv.cpp
  tests/meshcop/main.cpp
Labels: P3, cla: yes, enhancement

#195 [commissioner] move commissioner to src
  configure.ac
  src/Makefile.am
  src/commissioner/Makefile.am
  src/commissioner/addr_utils.cpp
  src/commissioner/addr_utils.hpp
  src/commissioner/commissioner.cpp
  src/commissioner/commissioner.hpp
  src/commissioner/commissioner_argcargv.cpp
  src/commissioner/commissioner_argcargv.hpp
  src/commissioner/commissioner_constants.hpp
  src/commissioner/commissioner_utils.hpp
  src/commissioner/device_hash.cpp
  src/commissioner/device_hash.hpp
  src/commissioner/joiner_session.cpp
  src/commissioner/joiner_session.hpp
  src/commissioner/main.cpp
  tests/meshcop/Makefile.am
  tests/meshcop/meshcop
Labels: P3, cla: yes, comp: commissioner

#200 [travis] fix android check
  .travis.yml
  .travis/before_install.sh
  .travis/check-android-build
  .travis/script.sh
Labels: P2, cla: yes, continuous-integration, enhancement

#202 [dtls] fix infinite loop
  .codecov.yml
  src/agent/dtls_mbedtls.cpp
Labels: P3, bug, cla: yes
