Repository openthread/ot-br-posix, pull requests merged in 2018-10, with the labels that each got.

#210 [libc] do not use glibc-internal header sys/cdefs.h
  third_party/wpantund/repo/src/util/string-utils.h
  third_party/wpantund/repo/src/wpantund/wpan-error.h
  third_party/wpantund/repo/third_party/openthread/src/ncp/spinel.h
Labels: cla: yes, enhancement

#216 [bootstrap] install automake and autoconf
  script/bootstrap
Labels: P4, cla: yes, enhancement

#217 [bootstrap] use iputils-ping instead of inetutils-ping
  script/bootstrap
Labels: P4, cla: yes, enhancement

#218 [systemd] fix unit file installation path
  configure.ac
  src/agent/Makefile.am
  src/web/Makefile.am
  third_party/wpantund/Makefile.am
Labels: P3, cla: yes, enhancement

#215 [commissioner] use getopt
  src/commissioner/Makefile.am
  src/commissioner/commissioner_argcargv.cpp
  src/commissioner/commissioner_argcargv.hpp
  src/commissioner/commissioner_constants.hpp
  src/commissioner/device_hash.cpp
  src/commissioner/device_hash.hpp
  src/commissioner/main.cpp
  tests/meshcop/meshcop
Labels: P4, cla: yes, comp: commissioner, enhancement

#219 [commissioner] fix missing help
  src/commissioner/commissioner_argcargv.cpp
Labels: P3, cla: yes, enhancement
