Repository openthread/ot-br-posix, pull requests merged in 2019-02, with the labels that each got.

#238 [docs] update version
  NOTICE
Labels: P4, cla: yes, comp: docs, enhancement

#239 [web] web commissioner
  .travis/script.sh
  src/commissioner/Makefile.am
  src/commissioner/commissioner.cpp
  src/commissioner/commissioner.hpp
  src/web/Makefile.am
  src/web/web-service/web_server.cpp
  src/web/web-service/web_server.hpp
  src/web/web-service/wpan_service.cpp
  src/web/web-service/wpan_service.hpp
  tests/scripts/meshcop
Labels: cla: yes

#241 [border-agent] ncp_wpatund.cpp: Fix off-by-one strncpy
  src/agent/ncp_wpantund.cpp
Labels: cla: yes

#240 [web] Web commissioner front end
  src/web/web-service/frontend/index.html
  src/web/web-service/frontend/res/css/styles.css
  src/web/web-service/frontend/res/js/app.js
Labels: cla: yes

#246 [style] remove snake case from style guide
  STYLE_GUIDE.md
Labels: cla: yes

#247 [web] fix print warning
  src/web/wpan-controller/dbus_get.cpp
Labels: P4, bug, cla: yes, comp: web service

#252 [web] fix network prefix with wpantund
  src/web/web-service/wpan_service.cpp
  tests/scripts/meshcop
Labels: cla: yes

#253 [style] upgrade to clang-format-6.0
  .script/clang-format.sh
  .travis.yml
  STYLE_GUIDE.md
Labels: P4, cla: yes, enhancement

#255 [commissioner] PSKd is required
  script/test
  src/commissioner/commissioner_argcargv.cpp
  src/commissioner/joiner_session.cpp
Labels: P4, bug, cla: yes, comp: commissioner

#256 [commissioner] ensure close notify on close
  src/commissioner/main.cpp
Labels: cla: yes, comp: border-agent, comp: commissioner, enhancement
