Repository openthread/ot-br-posix, pull requests merged in 2019-01, with the labels that each got.

#233 [script] enhance test script
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  configure.ac
  script/test
  tests/Makefile.am
  tests/meshcop/Makefile.am
  tests/meshcop/README.md
  tests/meshcop/meshcop_ftd
  tests/meshcop/meshcop_mtd
  tests/scripts/meshcop
  tools/Makefile.am
Labels: cla: yes, continuous-integration, enhancement

#234 [commissioner] fix typo in help
  src/commissioner/commissioner_argcargv.cpp
Labels: P4, cla: yes, comp: docs, enhancement

#236 [script] add avahi to server script
  script/server
Labels: cla: yes

#237 [init-scripts] make init scripts robust to stale pid files
  src/agent/otbr-agent.init.in
  src/web/otbr-web.init.in
  third_party/wpantund/wpantund.init
Labels: cla: yes

#232 [agent] parse xpanid in byte array format
  .travis.yml
  .travis/script.sh
  script/test
  src/agent/ncp_wpantund.cpp
  src/web/Makefile.am
  src/web/main.cpp
  tests/scripts/meshcop
Labels: cla: yes
