Repository openthread/ot-br-posix, pull requests merged in 2019-03, with the labels that each got.

#259 [docs] update repo name to ot-br-posix
  CONTRIBUTING.md
  README.md
Labels: cla: yes

#260 [agent] allow no mDNS
  .travis.yml
  .travis/check-android-build
  Android.mk
  configure.ac
  src/agent/border_agent.cpp
Labels: P4, cla: yes, comp: border-agent, enhancement

#263 [android] allow build without OpenThread repo
  Android.mk
  src/agent/Makefile.am
  src/agent/agent_instance.hpp
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.hpp
  src/commissioner/Makefile.am
  src/commissioner/commissioner.hpp
  src/commissioner/joiner_session.hpp
  src/common/Makefile.am
  src/common/coap.hpp
  src/common/coap_libcoap.cpp
  src/common/coap_libcoap.hpp
  src/common/dtls.hpp
  src/common/dtls_mbedtls.cpp
  src/common/dtls_mbedtls.hpp
  src/common/libcoap.h
  src/common/mainloop.h
  src/utils/Makefile.am
  tests/unit/test_coap.cpp
  tools/Makefile.am
Labels: P2, cla: yes, comp: build
