Repository openthread/ot-br-posix, pull requests merged in 2019-10, with the labels that each got.

#339 [script] avoid bash extension
  .travis/check-raspbian
  script/_initrc
Labels: cla: yes, enhancement

#341 [travis] fix homebrew with forced reinstall
  .travis/before_install.sh
Labels: P4, cla: yes, continuous-integration, enhancement

#337 [ncp] fix the default return value of RequestEvent
  src/agent/ncp_openthread.cpp
Labels: cla: yes, enhancement

#342 [docs] remove AppVeyor from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, comp: docs, enhancement
