Repository openthread/ot-br-posix, pull requests merged in 2019-07, with the labels that each got.

#311 [travis] fix mdns_mojo check
  tests/mdns/mdns_mojo_test/BUILD.gn
  tests/mdns/mdns_mojo_test/standalone_mojo_broker_lite.cpp
  tests/mdns/test-mojo
Labels: cla: yes, continuous-integration

#290 [docker] reduce image size
  etc/docker/Dockerfile
Labels: P4, cla: yes, enhancement

#312 [build] fix build without dbus
  configure.ac
  src/agent/Makefile.am
  third_party/wpantund/Makefile.am
Labels: cla: yes, comp: build, enhancement

#313 [mdns] support multiple services in mdns mojo agent
  src/agent/mdns_mojo.cpp
  src/agent/mdns_mojo.hpp
Labels: cla: yes, comp: border-agent, enhancement
