Repository openthread/ot-br-posix, pull requests merged in 2019-09, with the labels that each got.

#316 [openwrt] change Makefile github address to openwrt branch
  README.md
  feeds.conf
  openthread/Makefile
Labels: cla: yes

#325 [coap] fix write outside buffer bounds
  src/common/coap_libcoap.cpp
Labels: P3, bug, cla: yes

#329 [border-agent] fix mDNS with mojo initialization issue (#328)
  etc/libchrome_stub/third_party/chromecast/mojom/mdns.mojom.h
  src/agent/border_agent.cpp
  src/agent/mdns_mojo.cpp
  src/agent/mdns_mojo.hpp
  tests/mdns/mdns_mojo_test/client.cpp
Labels: P2, bug, cla: yes

#330 [mojo] check broker access before connection
  etc/libchrome_stub/third_party/chromecast/mojom/mdns.mojom.h
  src/agent/mdns_mojo.cpp
  src/agent/mdns_mojo.hpp
Labels: P3, cla: yes, enhancement

#335 [build] fix on macOS
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  script/_initrc
  script/bootstrap
  src/agent/ncp_wpantund.cpp
  src/commissioner/commissioner_argcargv.cpp
  src/common/dtls_mbedtls.cpp
Labels: P4, cla: yes, enhancement
