Repository openthread/ot-br-posix, pull requests merged in 2019-04, with the labels that each got.

#266 [docker] add syslog to docker image
  etc/Dockerfile
  script/server
Labels: P4, cla: yes, enhancement

#268 [logging] do not log to stderr by default
  src/agent/border_agent.cpp
  src/agent/main.cpp
  src/agent/mdns_avahi.cpp
  src/agent/mdns_mdnssd.cpp
  src/agent/ncp_wpantund.cpp
  src/commissioner/main.cpp
  src/common/logging.cpp
  src/common/logging.hpp
  src/web/main.cpp
  tests/mdns/main.cpp
  tests/scripts/meshcop
  tests/unit/test_logging.cpp
Labels: P4, cla: yes, enhancement

#271 [build] allow no boost
  configure.ac
Labels: P2, cla: yes, comp: build, enhancement

#272 [agent] configure service user
  configure.ac
  src/agent/otbr-agent.conf.in
Labels: P2, cla: yes, comp: border-agent, enhancement

#275 [agent] fix build on Android
  .travis/check-android-build
  Android.mk
Labels: P2, cla: yes, comp: border-agent

#277 [script] fix script for docker
  .travis/check-docker
  etc/docker/Dockerfile
  etc/docker/docker_entrypoint.sh
  script/bootstrap
Labels: cla: yes

#281 [web] unify start environment name
  src/web/otbr-web.init.in
  src/web/otbr-web.service.in
Labels: cla: yes
