Repository openthread/ot-br-posix, pull requests merged in 2019-05, with the labels that each got.

#282 [docker] do not fail on submodule update failure
  script/bootstrap
Labels: cla: yes

#283 [docker] add build status badges
  README.md
Labels: cla: yes, comp: docs, continuous-integration

#286 [docker] install git in Dockerfile
  etc/docker/Dockerfile
  script/bootstrap
Labels: bug, cla: yes, continuous-integration

#285 [web] fix commission alert message
  src/web/web-service/frontend/res/js/app.js
Labels: cla: yes

#288 [docker] remove src directory to reduce size
  etc/docker/Dockerfile
  script/_initrc
Labels: cla: yes

#294 [border-agent] do not start if PSKc is not initialized
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
Labels: P2, cla: yes, enhancement

#293 [build] switch to c++11
  STYLE_GUIDE.md
  configure.ac
  src/web/Makefile.am
Labels: P3, cla: yes, comp: build
