Repository openthread/ot-br-posix, pull requests merged in 2020-07, with the labels that each got.

#500 [style] fix a warning on c++11
  tests/unit/test_dbus_message.cpp
Labels: cla: yes

#503 [log] fix openthread logging not availbe upon init
  src/agent/main.cpp
  src/agent/ncp_openthread.cpp
Labels: cla: yes

#505 [dbus] fix handler registration under external reset
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
Labels: cla: yes

#506 [mdns] fix avahi size check
  src/mdns/mdns_avahi.cpp
Labels: bug, cla: yes

#508 [docker] support build environment
  .travis.yml
  .travis/check-docker
  etc/docker/Dockerfile
Labels: cla: yes

#509 [logging] remove unused setter
  src/common/logging.cpp
  src/common/logging.hpp
Labels: cla: yes

#511 [style] set c standard to c99
  CMakeLists.txt
Labels: cla: yes

#512 [test] add other nodes in the dbus test
  script/test
  tests/dbus/CMakeLists.txt
  tests/dbus/test-client
  tests/dbus/test_dbus_client.cpp
Labels: cla: yes

#513 [web] fix reflected XSS
  src/web/web-service/web_server.cpp
Labels: bug, cla: yes, comp: web service

#514 [cmake] move minimum version to 3.10.2
  CMakeLists.txt
  src/dbus/common/CMakeLists.txt
  src/web/CMakeLists.txt
  tests/unit/CMakeLists.txt
Labels: P4, cla: yes, comp: build, continuous-integration, enhancement

#516 [travis-ci] fix install python
  .travis/script.sh
Labels: P4, cla: yes, continuous-integration

#517 [joiner] fix joining behavior
  src/agent/thread_helper.cpp
  tests/dbus/test-client
  tests/scripts/bootstrap.sh
Labels: bug, cla: yes

#522 [build] fix build with BUILD_SHARED_LIBS=ON
  CMakeLists.txt
  src/dbus/server/CMakeLists.txt
Labels: cla: yes

#523 [github-actions] fix repo name in docker workflow
  .github/workflows/docker.yml
Labels: P4, bug, cla: yes, continuous-integration

#524 [ncp] fix legacy prefix handling
  Android.mk
  src/agent/ncp_openthread.cpp
  src/dbus/server/dbus_thread_object.cpp
Labels: cla: yes

#525 [doc] add GitHub Action badges for Build and Docker
  README.md
Labels: cla: yes, comp: docs

#526 [mdns] fix crash upon avahi access error
  src/mdns/mdns_avahi.cpp
Labels: bug, cla: yes
