Repository openthread/ot-br-posix, pull requests merged in 2020-12, with the labels that each got.

#632 [cli] fix reset command
  src/agent/main.cpp
Labels: cla: yes

#640 [github-actions] switch to ubuntu 20.04
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/macOS.yml
  .github/workflows/raspbian.yml
  tests/scripts/bootstrap.sh
Labels: cla: yes, continuous-integration

#639 [ncp] re-attach when soft reset is triggered
  src/agent/ncp_openthread.cpp
Labels: bug, cla: yes

#633 [otbr-web] fix Status page exception
  src/web/web-service/wpan_service.cpp
Labels: bug, cla: yes, comp: web service

#646 [dhcp6] enable DHCP6 server and client for reference device
  script/_otbr
Labels: P3, certification, cla: yes

#651 [test] move all jobs to GitHub Actions
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/meshcop.yml
  .github/workflows/openwrt.yml
  .travis.yml
  .travis/after_success.sh
  .travis/script.sh
  tests/scripts/check-docker
  tests/scripts/openwrt
Labels: P4, cla: yes, continuous-integration, enhancement

#656 [radio] pass full power map in command line args
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/dbus/server/dbus_thread_object.cpp
  tests/dbus/test-client
Labels: cla: yes

#658 [mbedtls] enable ECDSA support
  third_party/openthread/mbedtls-config.h
Labels: cla: yes

#657 Remove region from otbr-agent
  Android.mk
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/agent/thread_helper.cpp
  src/common/CMakeLists.txt
  src/common/region_code.cpp
  src/common/region_code.hpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  tests/dbus/test-client
  tests/dbus/test_dbus_client.cpp
Labels: cla: yes

#665 [utils] use keyword "override" for virtual methods
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.hpp
Labels: cla: yes

#662 [dbus] add active dataset api
  src/agent/thread_helper.cpp
  src/agent/thread_helper.hpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/common/dbus_message_helper.cpp
  src/dbus/common/dbus_message_helper.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  tests/dbus/test_dbus_client.cpp
Labels: cla: yes

#667 [ncp] initialize OT instance to nullptr in the constructor
  src/agent/ncp_openthread.cpp
Labels: cla: yes

#663 [utils] add gitignores for CLion
  .gitignore
Labels: cla: yes

#654 [codecov] fix codecov drop
  .github/workflows/build.yml
Labels: cla: yes, continuous-integration
