Repository openthread/ot-br-posix, pull requests merged in 2020-05, with the labels that each got.

#418 [openwrt] update doc to use `service`
  etc/openwrt/openthread-br/README.md
Labels: P4, cla: yes, comp: docs, enhancement

#429 [openthread] set runtime data file path
  third_party/openthread/CMakeLists.txt
Labels: P3, cla: yes, comp: build, enhancement

#425 [script] shallow initialize submodules
  script/bootstrap
Labels: P4, cla: yes, comp: build, enhancement

#430 [continuous-integration] move android build to github action
  .github/workflows/build.yml
  .travis.yml
  tests/scripts/bootstrap.sh
  tests/scripts/check-android-build
Labels: cla: yes, continuous-integration

#432 [dbus] add introspect interface
  .gitignore
  Android.mk
  src/agent/otbr-agent.conf.in
  src/dbus/common/constants.hpp
  src/dbus/server/CMakeLists.txt
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  tests/dbus/test-client
Labels: cla: yes

#436 [continuous-integration] move raspbian check to github actions
  .github/workflows/build.yml
  .travis.yml
  .travis/script.sh
  tests/scripts/bootstrap.sh
  tests/scripts/check-raspbian
Labels: P4, cla: yes, continuous-integration, enhancement

#437 [build] remove autoconf config.h
  include/openthread-br/config.h
Labels: cla: yes, comp: build, enhancement

#438 [continuous-integration] migrate build checks to github actions
  .github/workflows/build.yml
  .travis.yml
  .travis/script.sh
  tests/scripts/bootstrap.sh
  tests/scripts/check-scan-build
  tests/scripts/check-scripts
Labels: cla: yes, continuous-integration, enhancement

#441 [agent] fix state change handler logic
  src/agent/ncp_openthread.cpp
Labels: P4, bug, cla: yes, comp: border router
