Repository openthread/ot-br-posix, pull requests merged in 2020-11, with the labels that each got.

#602 [openwrt] fix otbr attempt to call global 'threadget' (a nil value)
  src/openwrt/view/admin_thread/thread_setting.htm
Labels: cla: yes

#591 [github-actions] build docker image for reference device
  .github/workflows/docker.yml
Labels: Thread 1.2, cla: yes, continuous-integration, enhancement

#603 [pretty] downgrade to clang-format v9.0
  CONTRIBUTING.md
  STYLE_GUIDE.md
  script/clang-format
  tests/scripts/bootstrap.sh
Labels: cla: yes

#605 [openwrt] fix startup script no effect
  src/openwrt/otbr-agent.init.in
Labels: bug, cla: yes

#606 [code-utils] remove client dependency of toolchain.h
  src/common/code_utils.hpp
Labels: bug, cla: yes, comp: build

#607 [cli] add cli support for region code
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  tests/dbus/test-client
Labels: cla: yes

#614 [docker] fix arm/v7 docker build
  .github/workflows/docker.yml
  etc/docker/Dockerfile
Labels: P1, cla: yes, platform: docker

#617 [docker] build docker images using both bionic and focal
  .github/workflows/docker.yml
  etc/docker/Dockerfile
Labels: P0, cla: yes, continuous-integration, platform: docker

#621 [test] fix build check on macOS
  .github/workflows/macOS.yml
  .travis.yml
  .travis/script.sh
Labels: cla: yes, continuous-integration

#618 [openwrt] fix rloc16 in little endian system
  src/openwrt/ubus/otubus.cpp
Labels: P4, bug, cla: yes, platform: openwrt

#619 [rest] fix show ip address on little endian system
  src/rest/json.cpp
  tests/rest/test_rest.py
Labels: P4, bug, cla: yes, comp: web service

#622 [agent] fix the process of generating extPanId
  src/agent/thread_helper.cpp
Labels: P3, bug, cla: yes

#623 [nit] fix BACKBONE_ROUTER readonly warning
  script/_otbr
Labels: P4, cla: yes

#626 [openthread] always enable SLAAC in ot-br-posix
  third_party/openthread/CMakeLists.txt
Labels: cla: yes, comp: build, enhancement

#625 [dbus] fix typo
  src/dbus/server/dbus_thread_object.cpp
Labels: P4, cla: yes, comp: dbus, enhancement

#624 [script] disable DNS of dnsmasq when DNS64 is on
  script/_network_manager
Labels: P4, bug, cla: yes, enhancement

#628 [plat] set gPlatResetReason for software reset
  src/agent/ncp_openthread.cpp
Labels: cla: yes

#630 [script] fix starting network manager
  script/_network_manager
  tests/scripts/check-scripts
Labels: cla: yes
