Repository openthread/ot-br-posix, pull requests merged in 2020-01, with the labels that each got.

#356 [travis] use bionic
  .travis.yml
  .travis/before_install.sh
  .travis/check-raspbian
  configure.ac
  script/_otbr
  script/_wpantund
  script/bootstrap
  tests/scripts/meshcop
  tests/unit/test_event_emitter.cpp
  tests/unit/test_logging.cpp
Labels: P4, cla: yes, comp: build, enhancement

#358 [travis] fix build errors
  .travis.yml
  .travis/check-posix
  tests/mdns/test-mojo
Labels: P3, bug, cla: yes, comp: build

#318 [script] call bootstrap in update
  script/update
Labels: P4, cla: yes, enhancement
