Repository openthread/ot-br-posix, pull requests merged in 2020-02, with the labels that each got.

#360 [dbus] introspect xml
  src/dbus/instropect.xml
Labels: P3, cla: yes, enhancement

#370 [build] use openthread-br/config.h
  Android.mk
  configure.ac
  include/Makefile.am
  include/openthread-br/config.h
  src/agent/Makefile.am
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/commissioner/Makefile.am
  src/common/Makefile.am
  src/dbus/Makefile.am
  src/utils/Makefile.am
  src/web/Makefile.am
  src/web/main.cpp
  src/web/web-service/wpan_service.hpp
  tests/dbus/Makefile.am
  tests/mdns/Makefile.am
  tests/unit/Makefile.am
  tools/Makefile.am
Labels: P4, cla: yes, comp: build, enhancement

#343 [mdns] don't include thread version if it is not available
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
Labels: cla: yes, enhancement

#375 [build] depend on OpenThread public headers only
  script/test
  src/agent/ncp.hpp
  src/web/web-service/ot_client.cpp
  third_party/openthread/openthread.mk
Labels: P4, cla: yes, comp: build, enhancement
