Repository openthread/ot-br-posix, pull requests merged in 2020-10, with the labels that each got.

#580 [clang-format] update to clang-format-10
  .clang-format
  .github/workflows/build.yml
  CONTRIBUTING.md
  STYLE_GUIDE.md
  script/clang-format
  tests/scripts/bootstrap.sh
Labels: P4, cla: yes, continuous-integration, enhancement

#566 [platform] verify Network Manager with BeagleBone
  examples/platforms/beagleboneblack/default
  script/_dhcpv6_pd
  script/_dns64
  script/_initrc
  script/_nat64
  script/_network_manager
Labels: cla: yes, comp: build, enhancement

#555 [dbus] add detailed dbus dump
  Android.mk
  src/common/code_utils.hpp
  src/dbus/common/CMakeLists.txt
  src/dbus/common/dbus_message_dump.cpp
  src/dbus/common/dbus_message_dump.hpp
  src/dbus/server/dbus_object.cpp
  src/dbus/server/dbus_object.hpp
  src/dbus/server/dbus_request.hpp
Labels: cla: yes

#584 [cmake] fix typo
  CMakeLists.txt
Labels: P4, cla: yes, enhancement

#585 [dockerfile] add more ARGs
  etc/docker/Dockerfile
Labels: P2, cla: yes, enhancement

#590 [web] fix OTBR-REST build fail in GCC 4.8.3
  .github/workflows/build.yml
  script/test
  src/rest/resource.cpp
  src/rest/resource.hpp
  src/rest/types.hpp
Labels: cla: yes

#583 [docker] compact docker image size
  etc/docker/Dockerfile
  script/bootstrap
Labels: P4, cla: yes, cleanup

#592 [dbus] fix using `dbusError` after free
  src/dbus/server/dbus_agent.cpp
Labels: P4, cla: yes, comp: dbus

#595 [docker] move to ubuntu 20.04
  etc/docker/Dockerfile
Labels: cla: yes

#597 [cmake] fix conditional inclusion of REST dependencies
  src/rest/CMakeLists.txt
  third_party/CMakeLists.txt
  third_party/http-parser/CMakeLists.txt
Labels: cla: yes, comp: build

#599 [docker] add backbone CI dependency
  etc/docker/Dockerfile
Labels: cla: yes

#579 [web-service] escape networkname
  src/web/web-service/wpan_service.cpp
  src/web/web-service/wpan_service.hpp
Labels: bug, cla: yes, comp: web service

#601 [common] remove client dependency of OpenThread header
  src/backbone_router/backbone_agent.cpp
  src/common/types.cpp
  src/common/types.hpp
Labels: bug, cla: yes, comp: build

#582 [cmake] update OT_LOG_LEVEL for debug build
  third_party/openthread/CMakeLists.txt
Labels: P4, cla: yes, enhancement

#567 [agent] add region support
  Android.mk
  src/agent/main.cpp
  src/agent/ncp_openthread.hpp
  src/agent/thread_helper.cpp
  src/common/CMakeLists.txt
  src/common/region_code.cpp
  src/common/region_code.hpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  tests/dbus/test-client
  tests/dbus/test_dbus_client.cpp
Labels: cla: yes
