Repository openthread/ot-br-posix, pull requests merged in 2020-09, with the labels that each got.

#551 [third-party] only add web related modules when necessary
  third_party/CMakeLists.txt
Labels: cla: yes

#556 [dockerfile] add ARG `OT_BACKBONE_CI`
  .github/workflows/docker.yml
  etc/docker/Dockerfile
Labels: Thread 1.2, cla: yes, comp: build, continuous-integration

#553 [flags] configure backbone network interface name
  CMakeLists.txt
  etc/docker/docker_entrypoint.sh
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
Labels: P2, Thread 1.2, cla: yes, comp: backbone router, enhancement

#563 [test] increase the waiting time in dbus tests
  tests/dbus/test-client
Labels: P2, cla: yes, continuous-integration

#558 [script] add `REFERENCE_DEVICE` support
  etc/docker/Dockerfile
  script/_otbr
Labels: certification, cla: yes

#564 [backbone-router] fix OT options for Backone Router
  CMakeLists.txt
Labels: P2, cla: yes, comp: backbone router

#572 [docker] add ca-certificates to DEPS
  etc/docker/Dockerfile
Labels: cla: yes

#571 [test] fix Thread node launch order
  tests/dbus/test-client
  tests/scripts/bootstrap.sh
Labels: cla: yes

#568 [mle] remove secure data request mode bit
  src/dbus/common/dbus_message_helper.hpp
  src/dbus/common/dbus_message_helper_openthread.cpp
  src/dbus/common/types.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/introspect.xml
  src/openwrt/ubus/otubus.cpp
  src/rest/json.cpp
  tests/dbus/test_dbus_client.cpp
  tests/rest/test_rest.py
  tests/unit/test_dbus_message.cpp
Labels: cla: yes

#574 [bootstrap] update brew install command
  tests/scripts/bootstrap.sh
Labels: cla: yes

#576 [github-actions] use docker/setup-buildx-action@v1
  .github/workflows/docker.yml
Labels: cla: yes, continuous-integration

#577 [web-service] use dataset command to form network
  src/web/web-service/wpan_service.cpp
Labels: P4, cla: yes, comp: web service, enhancement
