Repository openthread/ot-br-posix, pull requests merged in 2020-06, with the labels that each got.

#447 [continuous-integration] fix code coverage
  .github/workflows/build.yml
  .travis.yml
  .travis/script.sh
  etc/openwrt/openthread-br/Makefile
Labels: cla: yes, continuous-integration

#411 [script] add --no-install-recommends
  etc/docker/Dockerfile
  script/bootstrap
  script/standalone_ipv6
  tests/mdns/test-mojo
  tests/scripts/bootstrap.sh
Labels: P4, cla: yes, comp: build, continuous-integration, enhancement

#449 [agent] remove unused dtls session class
  src/agent/agent_instance.hpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.hpp
  src/common/dtls.hpp
  src/common/dtls_mbedtls.cpp
  src/common/dtls_mbedtls.hpp
  src/common/logging.cpp
  src/common/types.hpp
Labels: P4, cla: yes, cleanup

#451 [web] fix option require error in otbr-web
  src/web/main.cpp
Labels: cla: yes

#455 [logging] log package version as soon as possible
  Android.mk
  CMakeLists.txt
  doc/Doxyfile.in
  src/agent/main.cpp
  src/web/main.cpp
Labels: P4, cla: yes, comp: border router, comp: web service, enhancement

#457 [script] set build type to Debug by default
  script/test
Labels: P4, cla: yes, comp: build, enhancement

#460 [mdns] remove mojo support
  .github/workflows/build.yml
  .travis.yml
  .travis/script.sh
  Android.mk
  CMakeLists.txt
  etc/libchrome_stub/Android.mk
  etc/libchrome_stub/base/at_exit.h
  etc/libchrome_stub/base/bind.h
  etc/libchrome_stub/base/bind_helpers.h
  etc/libchrome_stub/base/command_line.h
  etc/libchrome_stub/base/embedder.h
  etc/libchrome_stub/base/logging.h
  etc/libchrome_stub/base/macros.h
  etc/libchrome_stub/base/message_loop/message_loop.h
  etc/libchrome_stub/base/message_loop/message_pump_for_io.h
  etc/libchrome_stub/base/scoped_ipc_support.h
  etc/libchrome_stub/base/task/message_loop_for_io.h
  etc/libchrome_stub/base/task_scheduler/post_task.h
  etc/libchrome_stub/chromecast/external_mojo/public/cpp/common.h
  etc/libchrome_stub/chromecast/external_mojo/public/cpp/external_connector.h
  etc/libchrome_stub/generate_mojom_sources.mk
  etc/libchrome_stub/mojo/core/embedder/embedder.h
  etc/libchrome_stub/mojo/core/embedder/scoped_ipc_support.h
  etc/libchrome_stub/third_party/chromecast/mojom/mdns.mojom.h
  src/mdns/CMakeLists.txt
  src/mdns/mdns_mojo.cpp
  src/mdns/mdns_mojo.hpp
  tests/mdns/CMakeLists.txt
  tests/mdns/mdns_mojo_test/BUILD.gn
  tests/mdns/mdns_mojo_test/client.cpp
  tests/mdns/mdns_mojo_test/public/mojom/BUILD.gn
  tests/mdns/mdns_mojo_test/standalone_mojo_broker_lite.cpp
  tests/mdns/mdns_mojo_test/stub_mojo_service.cpp
  tests/mdns/test-mojo
  tests/scripts/check-android-build
  third_party/chromecast/mojom/mdns.mojom
Labels: cla: yes

#461 [agent] add feature flags for unsecure join
  Android.mk
  CMakeLists.txt
  script/test
  src/agent/CMakeLists.txt
  src/agent/thread_helper.cpp
  src/dbus/server/dbus_thread_object.cpp
Labels: cla: yes, comp: build, enhancement

#462 [logging] remove unused file logging
  src/common/logging.cpp
  src/common/logging.hpp
Labels: P4, cla: yes, enhancement

#472 [cli] add radio version argument
  src/agent/main.cpp
  tests/dbus/test-client
Labels: cla: yes

#473 [script] try normal rm first
  script/test
Labels: P4, cla: yes, enhancement

#469 [mdns] publish binary xpanid in mdns text
  src/agent/border_agent.cpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_mdnssd.cpp
  tests/mdns/main.cpp
  tests/mdns/test-multiple
  tests/mdns/test-single
  tests/mdns/test-stop
  tests/mdns/test-update
Labels: P3, bug, cla: yes, comp: border router

#475 [etc] use /dev/ttyACM0 by default in /etc/default/otbr-agent
  src/agent/otbr-agent.default
Labels: cla: yes

#479 [dbus] remove dbus_message_helper.h from public include files
  src/dbus/client/thread_api_dbus.hpp
  tests/dbus/test_dbus_client.cpp
Labels: cla: yes

#480 [web] verbose invalid path exception
  src/web/web-service/web_server.cpp
Labels: P4, cla: yes, comp: web service, enhancement

#477 [style] remove NULL
  Android.mk
  src/agent/border_agent.cpp
  src/agent/main.cpp
  src/common/logging.cpp
  src/common/time.hpp
  src/dbus/server/dbus_agent.cpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.cpp
  src/mdns/mdns_mdnssd.hpp
  src/openwrt/ubus/otubus.cpp
  src/openwrt/ubus/otubus.hpp
  src/utils/pskc.cpp
  src/utils/strcpy_utils.cpp
  src/web/web-service/ot_client.cpp
  src/web/web-service/ot_client.hpp
  src/web/web-service/web_server.cpp
  src/web/web-service/web_server.hpp
  src/web/web-service/wpan_service.cpp
  tests/mdns/main.cpp
  tests/scripts/check-android-build
  tests/unit/test_dbus_message.cpp
  tests/unit/test_event_emitter.cpp
  tests/unit/test_mdns_mdnssd.cpp
  tests/unit/test_pskc.cpp
  third_party/openthread/mbedtls.mk
  third_party/openthread/openthread.mk
Labels: P4, cla: yes, cleanup, enhancement

#481 [script] set -x
  script/_initrc
Labels: P4, cla: yes, continuous-integration, enhancement

#484 [dbus] add group for client
  Android.mk
  src/agent/CMakeLists.txt
  src/agent/otbr-agent.conf.in
Labels: cla: yes

#487 [bootstrap] install dnsmasq with network-manager
  script/bootstrap
Labels: P3, bug, cla: yes, comp: build

#489 [scripts] fix ninja build log permissions
  script/_otbr
Labels: cla: yes

#490 [cmake] fix typo for OT_DAEMON
  third_party/openthread/CMakeLists.txt
Labels: cla: yes, comp: build, comp: docs

#492 [setup] fix network manager and DNS setup
  script/_dns64
  script/_network_manager
Labels: cla: yes

#494 Revert "[scripts] fix ninja build log permissions (#489)"
  script/_otbr
Labels: P1, bug, cla: yes

#476 [setup] allow specify cmake options via OS env
  script/_otbr
Labels: cla: yes
