Repository openthread/ot-br-posix, pull requests merged in 2020-03, with the labels that each got.

#377 [avahi] check if mGroup is nil before commit
  src/agent/mdns_avahi.cpp
Labels: bug, cla: yes

#378 [script] sync make-pretty scripts from openthread
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  CONTRIBUTING.md
  Makefile.am
  STYLE_GUIDE.md
  configure.ac
  script/clang-format
  script/clang-format-check
  script/make-pretty
  src/Makefile.am
  tests/mdns/mdns_mojo_test/client.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#380 [dbus] add handlers for managing external route
  script/clang-format
  src/agent/ncp_wpantund.cpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/common/dbus_message_helper_openthread.cpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/instropect.xml
  tests/dbus/test_dbus_client.cpp
Labels: cla: yes, enhancement

#382 [dbus] add get/set property logs
  src/dbus/server/dbus_object.cpp
Labels: cla: yes, enhancement

#383 [agent] use otbr log for OpenThread ncp
  src/agent/ncp_openthread.cpp
Labels: cla: yes, enhancement

#384 [agent] auto attach after reboot under daemon mode
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/agent/thread_helper.cpp
  src/agent/thread_helper.hpp
  tests/scripts/meshcop
Labels: cla: yes, enhancement

#381 [dbus] set steering data when permitting join
  .travis/check-android-build
  src/agent/thread_helper.cpp
  src/agent/thread_helper.hpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/instropect.xml
  third_party/openthread/Makefile.am
Labels: cla: yes, enhancement

#386 [android] fix android build with wpantund mode
  Android.mk
Labels: cla: yes

#387 [lgtm] add configuration file
  .lgtm.yml
Labels: P4, cla: yes, enhancement

#388 [android] fix deterministic -j1 build failure.
  .travis/check-android-build
  Android.mk
  etc/libchrome_stub/generate_mojom_sources.mk
Labels: cla: yes, comp: build
