Repository openthread/ot-br-posix, pull requests merged in 2021-07, with the labels that each got.

#918 [adproxy] erase outstanding updates before notifying the SRP server
  src/agent/advertising_proxy.cpp
Labels: bug, cla: yes, comp: dns

#924 [setup] fix libjsoncpp1 not found on Ubuntu 21.04
  .github/workflows/docker.yml
  etc/docker/Dockerfile
  script/bootstrap
Labels: bug, cla: yes

#929 [tests] add test for `FactoryReset` DBus API
  tests/dbus/test_dbus_client.cpp
Labels: P4, cla: yes, comp: dbus, continuous-integration, enhancement
