Repository openthread/ot-br-posix, pull requests merged in 2021-06, with the labels that each got.

#863 [github-actions] enable avahi for meshcop test in CI
  .github/workflows/meshcop.yml
Labels: cla: yes, comp: border router, comp: dns, continuous-integration

#877 [script] support OTBR_MDNS env variable in script/setup
  .github/workflows/border_router.yml
  etc/docker/Dockerfile
  script/_otbr
Labels: cla: yes, comp: dns, continuous-integration

#881 [web-service] fix form/join operations
  src/web/web-service/wpan_service.cpp
  src/web/web-service/wpan_service.hpp
Labels: bug, cla: yes, comp: web service

#867 [dns] fix potential Discovery Proxy crash
  src/agent/discovery_proxy.cpp
Labels: P2, bug, cla: yes, comp: dns

#883 [mdns] avahi publish an address/host with both IPv4 and IPv6
  src/mdns/mdns_avahi.cpp
Labels: bug, cla: yes, mdns

#875 [web] add pskd support for OTBR-WEB when joining an existing network
  src/web/web-service/frontend/join.dialog.html
  src/web/web-service/frontend/res/js/app.js
  src/web/web-service/ot_client.cpp
  src/web/web-service/ot_client.hpp
  src/web/web-service/web_server.cpp
  src/web/web-service/web_server.hpp
  src/web/web-service/wpan_service.cpp
  src/web/web-service/wpan_service.hpp
Labels: cla: yes, enhancement

#896 [cmake] include CoAPS PSK support for OTBR
  third_party/openthread/mbedtls-config.h
Labels: cla: yes, comp: build

#898 [test] fix OpenWrt check
  CMakeLists.txt
  etc/openwrt/openthread-br/Makefile
Labels: cla: yes, comp: build, platform: openwrt

#889 [network-key] change name from `master` to `network`
  src/agent/thread_helper.cpp
  src/agent/thread_helper.hpp
  src/common/types.hpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  src/openwrt/controller/thread.lua
  src/openwrt/ubus/otubus.cpp
  src/openwrt/ubus/otubus.hpp
  src/openwrt/view/admin_thread/thread_join.htm
  src/openwrt/view/admin_thread/thread_setting.htm
  src/web/web-service/frontend/index.html
  src/web/web-service/frontend/join.dialog.html
  src/web/web-service/frontend/res/js/app.js
  src/web/web-service/wpan_service.cpp
  src/web/web-service/wpan_service.hpp
  tests/dbus/test-client
  tests/dbus/test_dbus_client.cpp
  tests/scripts/check-docker
  tests/scripts/meshcop
Labels: P4, cla: yes

#902 [Android.mk] add missing Backbone Router sources
  Android.mk
  src/backbone_router/backbone_agent.cpp
  src/backbone_router/backbone_agent.hpp
Labels: bug, cla: yes, comp: backbone router, comp: build

#888 [adproxy] re-register all services when the mDNS publisher becomes ready
  src/agent/advertising_proxy.cpp
  src/agent/advertising_proxy.hpp
  src/agent/border_agent.cpp
  src/mdns/mdns.hpp
Labels: cla: yes, comp: border router, enhancement

#906 [dnssd] set TTL as 10 for entries discovered by avahi
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
Labels: cla: yes, comp: border router, comp: dns, mdns

#912 [github-actions] unify yaml indentations
  .github/workflows/border_router.yml
Labels: P4, cla: yes, continuous-integration
