Repository openthread/ot-br-posix, pull requests merged in 2021-03, with the labels that each got.

#713 [dbus] remove inclusion of code_utils.hpp in dbus api header
  src/dbus/client/thread_api_dbus.hpp
Labels: P1, bug, cla: yes

#649 [agent] full reset using execvp
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/rest/rest_web_server.cpp
  src/rest/rest_web_server.hpp
  src/utils/CMakeLists.txt
  src/utils/socket_utils.cpp
  src/utils/socket_utils.hpp
  tests/dbus/test-client
  tests/dbus/test_dbus_client.cpp
Labels: P0, bug, cla: yes, enhancement

#704 [dns-sd] implement missing Avahi bindings
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  tests/mdns/test-multiple-custom-hosts
  tests/mdns/test-single-custom-host
Labels: cla: yes, enhancement, mdns

#715 [backbone-router] add OTBR_DUA_ROUTING option (OFF by default)
  CMakeLists.txt
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/backbone_router/backbone_agent.cpp
  src/backbone_router/backbone_agent.hpp
  src/backbone_router/nd_proxy.cpp
  src/backbone_router/nd_proxy.hpp
  third_party/openthread/CMakeLists.txt
Labels: P1, Thread 1.2, cla: yes, comp: backbone router

#717 [build] add missing files for Android.mk
  Android.mk
Labels: cla: yes

#719 [utils] unify mainloop interface
  src/agent/agent_instance.cpp
  src/agent/agent_instance.hpp
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/backbone_router/backbone_agent.cpp
  src/backbone_router/backbone_agent.hpp
  src/backbone_router/nd_proxy.cpp
  src/backbone_router/nd_proxy.hpp
  src/common/CMakeLists.txt
  src/common/mainloop.hpp
  src/common/task_runner.cpp
  src/common/task_runner.hpp
  src/dbus/server/dbus_agent.cpp
  src/dbus/server/dbus_agent.hpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.cpp
  src/mdns/mdns_mdnssd.hpp
  src/rest/connection.cpp
  src/rest/connection.hpp
  src/rest/rest_web_server.cpp
  src/rest/rest_web_server.hpp
  tests/mdns/main.cpp
  tests/unit/test_task_runner.cpp
Labels: cla: yes, enhancement

#723 [git] reflect branch rename from 'master' to 'main'
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/documentation.yml
  .github/workflows/macOS.yml
  .github/workflows/meshcop.yml
  .github/workflows/openwrt.yml
  .github/workflows/raspbian.yml
  .gitmodules
  CONTRIBUTING.md
  README.md
  tests/scripts/meshcop
Labels: cla: yes, comp: docs, continuous-integration, enhancement

#724 [bbr] update Backbone Router configurations
  CMakeLists.txt
  src/backbone_router/backbone_agent.cpp
  third_party/openthread/CMakeLists.txt
Labels: P3, Thread 1.2, cla: yes, comp: backbone router

#712 [setup] enable IPv6 routing and DNS-based service discovery
  .github/workflows/build.yml
  .github/workflows/docker.yml
  CMakeLists.txt
  etc/docker/Dockerfile
  etc/docker/docker_entrypoint.sh
  examples/platforms/beagleboneblack/default
  examples/platforms/fedora/default
  examples/platforms/raspbian/default
  examples/platforms/ubuntu/default
  script/_border_routing
  script/_initrc
  script/_ipforward
  script/_otbr
  script/bootstrap
  script/console
  script/setup
  script/update
  src/agent/CMakeLists.txt
  src/agent/otbr-agent.default.in
  tests/scripts/check-docker
  tests/scripts/check-scripts
  third_party/openthread/CMakeLists.txt
Labels: P1, cla: yes, comp: border router

#726 [utils] post delayed tasks with TaskRunner
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/agent/thread_helper.cpp
  src/agent/thread_helper.hpp
  src/common/task_runner.cpp
  src/common/task_runner.hpp
  src/common/time.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  tests/unit/test_task_runner.cpp
Labels: cla: yes, enhancement

#733 [tests] pin cmake to version 3.10.3
  tests/scripts/check-raspbian
Labels: P1, bug, cla: yes, continuous-integration

#731 [advertising-proxy] fix unpublish a host
  src/agent/advertising_proxy.cpp
  src/agent/advertising_proxy.hpp
Labels: bug, cla: yes, comp: border router, mdns

#734 [github-actions] move backbone router tests to dedicated workflow
  .github/workflows/backbone_router.yml
  .github/workflows/build.yml
Labels: cla: yes

#721 [border-agent] advertise more meshcop service TXT entries
  .github/workflows/meshcop.yml
  Android.mk
  src/agent/CMakeLists.txt
  src/agent/agent_instance.cpp
  src/agent/agent_instance.hpp
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
  src/agent/main.cpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/backbone_router/backbone_agent.cpp
  src/backbone_router/backbone_agent.hpp
  src/common/byteswap.hpp
  src/mdns/mdns_avahi.hpp
  src/openwrt/ubus/otubus.cpp
  src/rest/connection.cpp
  src/rest/rest_web_server.hpp
  src/utils/CMakeLists.txt
  src/utils/event_emitter.cpp
  src/utils/event_emitter.hpp
  tests/scripts/bootstrap.sh
  tests/scripts/meshcop
  tests/unit/CMakeLists.txt
  tests/unit/test_event_emitter.cpp
Labels: cla: yes, enhancement, mdns

#743 [agent] print thread version at start
  src/agent/border_agent.cpp
  src/agent/main.cpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
Labels: cla: yes, enhancement

#738 [script] add the script to compile otbr-agent
  script/_otbr
  script/cmake-build
  script/test
Labels: P3, cla: yes, comp: build, enhancement

#751 [web] improve add/delete prefix functionality
  src/web/web-service/wpan_service.cpp
Labels: P4, cla: yes, comp: web service

#744 [config] add default configuration for platform debian
  examples/platforms/debian/default
Labels: cla: yes

#749 [dockerfile] fix docker build not fail when setup failed
  etc/docker/Dockerfile
Labels: P4, bug, cla: yes, platform: docker

#757 [github-action] remove use of mplatform/mquery in docker build
  .github/workflows/docker.yml
Labels: cla: yes, continuous-integration

#761 [github-actions] fix typo in docker workflow
  .github/workflows/docker.yml
Labels: bug, cla: yes, continuous-integration

#760 [mdns] fix deallocation of null pointers
  src/mdns/mdns_mdnssd.cpp
Labels: P4, bug, cla: yes, comp: dns

#754 [build] move cmake options to file options.cmake
  CMakeLists.txt
  etc/cmake/options.cmake
Labels: P3, cla: yes, comp: build, enhancement
