Repository openthread/ot-br-posix, pull requests merged in 2021-04, with the labels that each got.

#767 [dbus] add "Detach" API
  src/agent/thread_helper.cpp
  src/agent/thread_helper.hpp
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  tests/dbus/test-client
Labels: cla: yes, comp: dbus, enhancement

#706 [dnssd] implement DNS-SD Discovery Proxy
  Android.mk
  etc/cmake/options.cmake
  src/agent/CMakeLists.txt
  src/agent/advertising_proxy.cpp
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
  src/agent/discovery_proxy.cpp
  src/agent/discovery_proxy.hpp
  src/common/CMakeLists.txt
  src/common/code_utils.hpp
  src/common/dns_utils.cpp
  src/common/dns_utils.hpp
  src/common/types.cpp
  src/common/types.hpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.cpp
  src/mdns/mdns_mdnssd.hpp
  third_party/openthread/CMakeLists.txt
Labels: P1, cla: yes, comp: border router, comp: dns, enhancement, mdns

#776 [mdns] silence unused parameter warning when compiling without assert
  src/mdns/mdns_mdnssd.cpp
Labels: cla: yes

#782 [script] make sure to enable `tayga` on install
  script/_nat64
Labels: bug, cla: yes

#788 [github-actions] add `brew update`
  .github/workflows/macOS.yml
Labels: cla: yes, continuous-integration

#685 [web-service] fix parsing of ipv6 addresses for status page
  src/web/web-service/wpan_service.cpp
Labels: cla: yes

#797 [tests] wait longer for services to be ready
  tests/scripts/check-scripts
Labels: bug, cla: yes, continuous-integration

#799 [mdns] fix pointer to object on stack in TxtList
  src/mdns/mdns.cpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
Labels: bug, cla: yes, mdns

#792 [border-agent] use ephemeral port
  src/agent/border_agent.cpp
  src/web/web-service/wpan_service.cpp
  src/web/web-service/wpan_service.hpp
  tests/scripts/meshcop
Labels: cla: yes, enhancement

#795 [dns] enable DNS-SD Discovery Proxy
  script/_otbr
Labels: cla: yes, comp: border router, comp: dns, enhancement

#805 [doc] fix comment for mdnssd
  src/mdns/mdns_mdnssd.hpp
Labels: P4, cla: yes, comp: docs, mdns

#796 [web-service] catch exceptions in web server
  src/web/web-service/web_server.cpp
Labels: cla: yes, comp: web service

#750 [github-actions] add border router tests
  .github/workflows/border_router.yml
Labels: P4, cla: yes, comp: border router, continuous-integration

#764 [cmake] allow custom OTBR package name and package version
  CMakeLists.txt
  third_party/openthread/CMakeLists.txt
  third_party/openthread/mbedtls-config.h
Labels: cla: yes, comp: build

#813 [dhcpcd] unpin dhcpcd5 version
  script/bootstrap
  src/rest/resource.cpp
  third_party/dhcpcd/dhcpcd5_6.11.5-1+rpt2_armhf.deb
Labels: cla: yes

#820 [rest] release sockets in destructors
  src/rest/connection.cpp
  src/rest/connection.hpp
  src/rest/rest_web_server.cpp
  src/rest/rest_web_server.hpp
  tests/scripts/meshcop
Labels: cla: yes, comp: web service, continuous-integration

#824 [cmake] supress error message of getting git revision
  CMakeLists.txt
Labels: cla: yes, comp: build

#746 [logging] add the log tag to the logging APIs
  src/agent/advertising_proxy.cpp
  src/agent/agent_instance.cpp
  src/agent/border_agent.cpp
  src/agent/discovery_proxy.cpp
  src/agent/main.cpp
  src/agent/ncp_openthread.cpp
  src/agent/ncp_openthread.hpp
  src/agent/thread_helper.cpp
  src/agent/thread_helper.hpp
  src/backbone_router/backbone_agent.cpp
  src/backbone_router/nd_proxy.cpp
  src/common/code_utils.hpp
  src/common/logging.cpp
  src/common/logging.hpp
  src/common/task_runner.cpp
  src/dbus/common/dbus_message_dump.cpp
  src/dbus/server/dbus_agent.cpp
  src/dbus/server/dbus_object.cpp
  src/dbus/server/dbus_object.hpp
  src/dbus/server/dbus_request.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_mdnssd.cpp
  src/openwrt/ubus/otubus.cpp
  src/rest/resource.cpp
  src/rest/rest_web_server.cpp
  src/utils/pskc.cpp
  src/utils/system_utils.cpp
  src/web/main.cpp
  src/web/web-service/ot_client.cpp
  src/web/web-service/web_server.cpp
  src/web/web-service/wpan_service.cpp
  tests/unit/test_logging.cpp
Labels: P3, cla: yes, enhancement

#783 [dns] handle instance names with dots
  src/agent/discovery_proxy.cpp
  src/agent/discovery_proxy.hpp
  src/common/dns_utils.cpp
  src/common/dns_utils.hpp
  tests/unit/CMakeLists.txt
  tests/unit/test_dns_utils.cpp
Labels: P4, cla: yes, enhancement
