Repository openthread/ot-br-posix, pull requests merged in 2021-01, with the labels that each got.

#668 [dbus] add dbus api to get/set radio region
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  tests/dbus/test_dbus_client.cpp
Labels: cla: yes

#669 [mdns] accept a list of TXT entries
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.cpp
  src/mdns/mdns_mdnssd.hpp
  tests/mdns/main.cpp
Labels: cla: yes

#670 [doc] generate documentation
  .github/workflows/documentation.yml
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/Doxyfile.in
  include/openthread-br/config.h
  script/test
  src/agent/thread_helper.hpp
  src/common/byteswap.hpp
  src/common/code_utils.hpp
  src/common/logging.hpp
  src/common/time.hpp
  src/dbus/client/client_error.hpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/common/constants.hpp
  src/dbus/common/dbus_message_dump.hpp
  src/dbus/common/dbus_message_helper.hpp
  src/dbus/common/dbus_resources.hpp
  src/dbus/common/error.hpp
  src/dbus/common/types.hpp
  src/dbus/server/dbus_agent.hpp
  src/dbus/server/dbus_object.hpp
  src/dbus/server/dbus_request.hpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/error_helper.hpp
  src/openwrt/ubus/otubus.hpp
  src/utils/event_emitter.hpp
  src/utils/strcpy_utils.hpp
  src/web/web-service/ot_client.hpp
Labels: cla: yes, comp: docs

#672 [dbus] add detailed docs for dbus introspect xml
  src/dbus/server/introspect.xml
Labels: cla: yes, comp: dbus, comp: docs

#673 [github-actions] update raspbian to 2021-01-11
  .github/workflows/raspbian.yml
Labels: cla: yes, continuous-integration, enhancement

#671 [code-utils] separate toolchain header
  src/common/code_utils.hpp
  src/common/toolchain.hpp
  src/common/types.hpp
Labels: cla: yes

#675 [build] add Android.bp support
  Android.bp
  Android.mk
  tests/scripts/check-android-build
Labels: P3, cla: yes, comp: build

#677 [dbus] use recommended dbus dispatch style
  src/dbus/server/dbus_agent.cpp
Labels: cla: yes

#679 [dbus] add watch enable check
  src/dbus/server/dbus_agent.cpp
  src/dbus/server/dbus_agent.hpp
Labels: cla: yes

#676 [doc] add generated dbus doc to the doc site
  .github/workflows/documentation.yml
  doc/CMakeLists.txt
  src/dbus/server/CMakeLists.txt
  src/dbus/server/dbus_thread_object.hpp
Labels: cla: yes

#681 [github-actions] add apt-get update to documentation
  .github/workflows/documentation.yml
Labels: cla: yes, continuous-integration

#678 [build] add project extensions for Android.mk
  Android.mk
Labels: cla: yes

#680 [bootstrap] install dnsutils for reference device
  script/bootstrap
Labels: cla: yes, platform: docker

#682 [doc] fix doc build cmake flags
  .github/workflows/documentation.yml
Labels: cla: yes

#683 [github-actions] install libdbus-1-dev for docs build
  .github/workflows/documentation.yml
Labels: cla: yes, comp: docs, continuous-integration

#686 [build] make dbus user and group configurable in Android.mk
  Android.mk
Labels: P3, cla: yes, enhancement

#687 [build] eliminate generated files from the source directory
  Android.mk
  src/dbus/server/CMakeLists.txt
Labels: cla: yes, comp: build

#688 [dbus] fix wrong error code when error happens
  src/dbus/client/client_error.cpp
  src/dbus/client/thread_api_dbus.cpp
  tests/dbus/test-client
  tests/dbus/test_dbus_client.cpp
  tests/rest/test-rest-server
Labels: cla: yes
