Repository openthread/ot-br-posix, pull requests merged in 2021-08, with the labels that each got.

#949 [mdns] resolve service name conflicts when using avahi
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
Labels: comp: border router, cla: yes, mdns

#962 [docs] fix typos in mainloop.hpp
  src/common/mainloop.hpp
Labels: cla: yes

#960 [mdns] rename "MDNS" to "mDNS"
  CMakeLists.txt
  src/agent/border_agent.cpp
  src/common/types.hpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.hpp
Labels: cla: yes

#972 [test] fix parsing border agent port
  tests/scripts/meshcop
Labels: cla: yes

#976 [mdns] fix unused variable of aServiceRef
  src/mdns/mdns_mdnssd.cpp
Labels: cla: yes

#981 [github-actions] fix raspbian-check failure when `apt-get update`
  tests/scripts/check-raspbian
Labels: cla: yes

#975 [cmake] allow specifying vendor and product name
  CMakeLists.txt
Labels: comp: build, cla: yes, mdns

#986 [mdns-avahi] browse or resolve using unspecified protocol
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
Labels: bug, cla: yes, mdns, comp: dns

#995 [web] extend web client timeout
  src/web/web-service/ot_client.cpp
Labels: cla: yes
