Repository openthread/ot-br-posix, pull requests merged in 2021-02, with the labels that each got.

#692 [dbus] fix accidental line removal
  src/dbus/client/thread_api_dbus.cpp
Labels: cla: yes

#666 [dns-sd] initial implementation of the Advertising Proxy
  Android.mk
  CMakeLists.txt
  etc/docker/Dockerfile
  script/server
  src/agent/CMakeLists.txt
  src/agent/advertising_proxy.cpp
  src/agent/advertising_proxy.hpp
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
  src/agent/ncp_openthread.cpp
  src/common/types.cpp
  src/common/types.hpp
  src/mdns/CMakeLists.txt
  src/mdns/mdns.cpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_mdnssd.cpp
  src/mdns/mdns_mdnssd.hpp
  third_party/openthread/CMakeLists.txt
Labels: P3, cla: yes, enhancement

#695 [style] replace (void) with OTBR_UNUSED_VARIABLE
  src/agent/main.cpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/client/thread_api_dbus.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/mdns/mdns_mdnssd.cpp
  src/rest/resource.cpp
  src/web/web-service/web_server.cpp
  tests/unit/test_event_emitter.cpp
Labels: cla: yes

#703 [types] remove dependency of OpenThread header
  src/agent/advertising_proxy.cpp
  src/common/types.cpp
  src/common/types.hpp
Labels: P4, bug, cla: yes

#700 [dns-sd] use new DNS TXT entry iterator
  src/agent/advertising_proxy.cpp
Labels: P4, cla: yes, enhancement

#699 [common] add Task Runner
  src/common/CMakeLists.txt
  src/common/code_utils.hpp
  src/common/task_runner.cpp
  src/common/task_runner.hpp
  tests/unit/CMakeLists.txt
  tests/unit/test_task_runner.cpp
Labels: cla: yes

#708 [dbus] add missing header inclusion
  src/dbus/client/CMakeLists.txt
  src/dbus/client/thread_api_dbus.hpp
Labels: P4, bug, cla: yes, comp: dbus

#707 [netdiag] fix network diagnostic get response callback
  src/openwrt/ubus/otubus.cpp
  src/rest/resource.cpp
Labels: cla: yes

#711 [agent] print help message for backbone interface
  src/agent/main.cpp
Labels: cla: yes

#701 [mdns] advertise extended address as discriminator
  src/agent/border_agent.cpp
  src/agent/border_agent.hpp
  src/agent/ncp.hpp
  src/agent/ncp_openthread.cpp
  src/common/types.hpp
  src/mdns/mdns_avahi.cpp
  tests/mdns/main.cpp
  tests/mdns/test-multiple
  tests/mdns/test-single
  tests/mdns/test-stop
  tests/mdns/test-update
Labels: cla: yes
