Repository openthread/ot-br-posix, pull requests merged in 2022-08, with the labels that each got.

#1485 [tests] upgrade pip before installing cmake
  tests/scripts/bootstrap.sh
Labels: continuous-integration

#1482 [discovery-proxy] fix unused variable warning in release build
  src/sdp_proxy/discovery_proxy.cpp
Labels: comp: discovery proxy

#1488 [advertising-proxy] don't publish mesh local addresses for hosts
  src/sdp_proxy/advertising_proxy.cpp
  src/sdp_proxy/advertising_proxy.hpp
Labels: enhancement, P2, comp: advertising-proxy

#1491 [advertising-proxy] support publishing multiple host addresses
  src/mdns/mdns.cpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.cpp
  src/mdns/mdns_mdnssd.hpp
  src/sdp_proxy/advertising_proxy.cpp
  tests/mdns/main.cpp
Labels: mdns, comp: advertising-proxy

#1501 [github-actions] update settings for the border router nat64 CI tests
  .github/workflows/border_router.yml
Labels: continuous-integration

#1502 [github-actions] add NAT64 env
  .github/workflows/border_router.yml
Labels: continuous-integration

#1496 [script] don't use cached version strings if re-installing OTBR
  script/_otbr
Labels: comp: build

#1508 [docs] update Thread version
  NOTICE
Labels: comp: docs

#1516 [cmake] fix setting of `OT_TARGET_OPENWRT`
  third_party/openthread/CMakeLists.txt
Labels: comp: build, platform: openwrt

#1505 [nat64] support `OTBR_NAT64_BORDER_ROUTING` and `OTBR_BORDER_ROUTING_NAT64`
  .github/workflows/border_router.yml
  etc/cmake/options.cmake
  third_party/openthread/CMakeLists.txt
Labels: enhancement, comp: build
