Repository openthread/ot-br-posix, pull requests merged in 2022-03, with the labels that each got.

#1284 [build] update openthread cmake options
  third_party/openthread/CMakeLists.txt
Labels: P3, comp: build

#1290 [cmake] add `OTBR_NOTIFY_UPSTART` option
  etc/cmake/options.cmake
  src/agent/application.cpp
Labels: P2, comp: build

#1287 [firewall] clear firewall rules before starting a new firewall
  script/_firewall
  script/otbr-firewall
Labels: comp: border router

#1283 [avahi] bug fix and small enhancements for avahi publisher
  src/common/types.hpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
Labels: bug, P2, mdns, Avahi

#1293 [firewall] remove `-p ip` argument in ip6tables rules
  script/otbr-firewall
Labels: enhancement, comp: border router

#1289 [doxygen] change `[inout]` to `[in,out]`
  src/common/mainloop.hpp
  src/common/mainloop_manager.hpp
  src/rest/resource.hpp
  src/web/web-service/wpan_service.hpp
Labels: P4, comp: docs

#1296 [dbus] fix OTBR's behavior when `Reset` is invoked
  src/border_agent/border_agent.cpp
  src/sdp_proxy/advertising_proxy.cpp
  src/sdp_proxy/discovery_proxy.cpp
Labels: bug, P1, comp: dbus

#1301 [docs] community discussion change
  .github/ISSUE_TEMPLATE.md
  CMakeLists.txt
  README.md
Labels: comp: docs

#1307 [border-agent] don't treat `OTBR_ERROR_ABORTED` as an error in logs
  src/border_agent/border_agent.cpp
Labels: enhancement, mdns, border agent

#1310 [logging] use capitalized first letter for log messages
  src/sdp_proxy/discovery_proxy.cpp
Labels: comp: logging

#1300 [logging] refine mDNS logs
  src/mdns/mdns.cpp
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_mdnssd.cpp
Labels: P2, mdns, Avahi, mDNSResponder, comp: logging

#1291 [dns64] set DNS64 default value to 0
  etc/docker/Dockerfile
  etc/docker/docker_entrypoint.sh
  examples/platforms/beagleboneblack/default
  examples/platforms/raspbian/default
  examples/platforms/ubuntu/default
Labels: comp: dns
