Repository openthread/ot-br-posix, pull requests merged in 2022-01, with the labels that each got.

#1172 [utils] use `__FILE__` in failure logs
  src/common/code_utils.hpp
Labels: P4

#1165 [discovery-proxy] compare DNS labels in a case-insensitive manner
  src/sdp_proxy/discovery_proxy.cpp
  src/utils/CMakeLists.txt
  src/utils/string_utils.cpp
  src/utils/string_utils.hpp
Labels: bug, comp: discovery proxy

#1177 [utils] add `NonCopyable`
  src/agent/application.hpp
  src/agent/instance_params.hpp
  src/backbone_router/backbone_agent.hpp
  src/backbone_router/dua_routing_manager.hpp
  src/backbone_router/nd_proxy.hpp
  src/border_agent/border_agent.hpp
  src/common/code_utils.hpp
  src/common/mainloop_manager.hpp
  src/common/task_runner.hpp
  src/dbus/server/dbus_agent.hpp
  src/dbus/server/dbus_object.hpp
  src/mdns/mdns.hpp
  src/mdns/mdns_avahi.hpp
  src/mdns/mdns_mdnssd.hpp
  src/sdp_proxy/advertising_proxy.hpp
  src/sdp_proxy/discovery_proxy.hpp
Labels: enhancement, P4

#1178 [mdnssd] call `DNSServiceProcessResult` at the end of `Process`
  src/mdns/mdns_mdnssd.cpp
  src/mdns/mdns_mdnssd.hpp
Labels: bug, mdns, mDNSResponder

#1173 [agent] refactor radio version printing
  src/agent/application.cpp
  src/agent/application.hpp
  src/agent/main.cpp
  src/border_agent/border_agent.hpp
  src/ncp/ncp_openthread.cpp
  src/ncp/ncp_openthread.hpp
  src/rest/resource.cpp
Labels: P2

#1185 [certification] return ipv6 in testharness-discovery script
  tools/reference_device/testharness-discovery
Labels: certification

#1175 [dbus] retry on failures when connecting to DBus
  script/test
  src/dbus/server/dbus_agent.cpp
  src/dbus/server/dbus_agent.hpp
Labels: comp: dbus

#1183 [application] de-initialize `Application` and OpenThread instance
  src/agent/application.cpp
  src/agent/application.hpp
  src/agent/main.cpp
  src/border_agent/border_agent.cpp
  src/border_agent/border_agent.hpp
  src/ncp/ncp_openthread.cpp
  src/ncp/ncp_openthread.hpp
Labels: enhancement, P2

#1198 [dbus] fix dbus reconnection
  src/dbus/server/dbus_agent.cpp
  src/dbus/server/dbus_agent.hpp
Labels: enhancement, comp: dbus

#1204 [mdns] add debug logging for the mDNSResponder publisher
  src/mdns/mdns_mdnssd.cpp
Labels: enhancement, mdns, mDNSResponder

#1206 [github-actions] border_router test enhancements
  .github/workflows/border_router.yml
Labels: enhancement, continuous-integration

#1212 [test] use cmake to build ot-rcp
  tests/scripts/check-scripts
Labels: comp: build

#1217 [certification] disable auto Thread attaching for Reference Device
  script/_otbr
  src/agent/CMakeLists.txt
  src/agent/otbr-agent.default.in
  src/ncp/ncp_openthread.cpp
  src/ncp/ncp_openthread.hpp
Labels: enhancement, P2, certification

#1214 [dbus] refine DBus `GetProperty` error logs
  src/dbus/server/dbus_object.cpp
Labels: enhancement, P4, comp: dbus
