Repository openthread/ot-br-posix, pull requests merged in 2023-01, with the labels that each got.

#1684 [continuous-integration] fix macOS for Python 3.11
  .github/workflows/macOS.yml
Labels: continuous-integration

#1692 [config] add the otbr posix config file
  src/agent/openthread-otbr-posix-config.h
  third_party/openthread/CMakeLists.txt
Labels: enhancement, P3

#1702 [openthread] disable power calibration
  third_party/openthread/CMakeLists.txt
Labels: enhancement, P3

#1701 [test] move the config file to the correct path for testing
  tests/dbus/CMakeLists.txt
  tests/dbus/test-client
  third_party/openthread/CMakeLists.txt
Labels: bug, P3

#1690 [border-agent] refactor `BorderAgent::PublishMeshCopService()`
  src/border_agent/border_agent.cpp
  src/border_agent/border_agent.hpp
Labels: border agent

#1705 [telemetry] infra link information
  src/dbus/common/constants.hpp
  src/dbus/common/dbus_message_helper.hpp
  src/dbus/common/dbus_message_helper_openthread.cpp
  src/dbus/common/types.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
Labels: comp: dbus, comp: telemetry

#1713 [rest] remove superfluous space in HTTP status line
  src/rest/response.cpp
Labels: comp: web service

#1673 [openwrt] update the Makefile and init scripts
  etc/openwrt/openthread-br/Makefile
  etc/openwrt/openthread-br/README.md
  src/openwrt/CMakeLists.txt
  src/openwrt/otbr-agent.init.in
  src/openwrt/otbr-agent.uci-config.in
  src/openwrt/otbr-firewall.init.in
  src/openwrt/ubus/otubus.cpp
  src/openwrt/ubus/otubus.hpp
  src/openwrt/view/admin_thread/thread_overview.htm
  tests/scripts/openwrt
Labels: comp: build, platform: openwrt
