Repository openthread/ot-br-posix, pull requests merged in 2023-06, with the labels that each got.

#1826 [nat64] add DBus API for setting NAT64 CIDR during runtime
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
Labels: enhancement

#1897 [github-actions] fix macOS workflow error due to protobuf library
  .github/workflows/macOS.yml
  src/proto/CMakeLists.txt
Labels: continuous-integration

#1901 [github-actions] run `tests/scripts/bootstrap.sh` for doc gen
  .github/workflows/documentation.yml
Labels: continuous-integration

#1902 [github-actions] specify `BUILD_TARGET` in doc workflow
  .github/workflows/documentation.yml
Labels: continuous-integration

#1910 [mdns] pass copy of `mType` for `OnServiceResolved`
  src/mdns/mdns.cpp
  src/mdns/mdns.hpp
Labels: bug, mdns

#1909 [build] add -rdynamic to the linker flags
  CMakeLists.txt
Labels: enhancement, P3, comp: build

#1911 [mdns] all `On{Item}Resolved()` callbacks to use value parameters
  src/mdns/mdns.cpp
  src/mdns/mdns.hpp
Labels: bug, mdns

#1913 [callback] update `OnceCallback` to clear moved-from rvalue reference
  src/common/callback.hpp
Labels: bug, P4
