Repository openthread/ot-br-posix, pull requests merged in 2023-05, with the labels that each got.

#1682 [rest] add Operational Dataset API
  src/rest/json.cpp
  src/rest/json.hpp
  src/rest/openapi.yaml
  src/rest/parser.cpp
  src/rest/request.cpp
  src/rest/request.hpp
  src/rest/resource.cpp
  src/rest/resource.hpp
  src/rest/response.cpp
  src/rest/response.hpp
  src/rest/types.hpp
  src/utils/hex.cpp
  src/utils/hex.hpp
Labels: comp: web service

#1857 [openwrt] update docker image `openwrtorg/sdk` to `openwrt/sdk`
  tests/scripts/openwrt
Labels: continuous-integration, platform: openwrt

#1862 [rest] allow to specify REST listen port
  src/agent/application.cpp
  src/agent/application.hpp
  src/agent/main.cpp
  src/rest/rest_web_server.cpp
  src/rest/rest_web_server.hpp
Labels: comp: web service

#1864 [rest] return border agent ID
  src/rest/json.cpp
  src/rest/openapi.yaml
  src/rest/resource.cpp
  src/rest/resource.hpp
  src/rest/types.hpp
Labels: comp: web service

#1866 [rest] support Thread state change
  src/common/CMakeLists.txt
  src/common/api_strings.cpp
  src/common/api_strings.hpp
  src/dbus/client/thread_api_dbus.cpp
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/rest/json.cpp
  src/rest/json.hpp
  src/rest/openapi.yaml
  src/rest/resource.cpp
  src/rest/resource.hpp
  src/rest/types.hpp
  tests/rest/test_rest.py
Labels: comp: web service

#1876 [scripts] install `avahi-utils` in `script/bootstrap`
  script/bootstrap
Labels: continuous-integration

#1881 [openwrt] load D3.js over webserver protocol
  src/openwrt/view/admin_thread/thread_view.htm
Labels: platform: openwrt
