Repository openthread/ot-br-posix, pull requests merged in 2023-03, with the labels that each got.

#1774 [rest] explicitly set Connection header to close
  src/rest/response.cpp
Labels: comp: web service

#1791 [build] add build option OTBR_RADIO_URL for setting the radio URL
  CMakeLists.txt
  src/agent/otbr-agent.default.in
Labels: enhancement, P4, comp: build

#1777 [dnssd] add support for upstream DNS query APIs
  etc/cmake/options.cmake
  src/dbus/common/constants.hpp
  src/dbus/common/dbus_message_helper.hpp
  src/dbus/server/dbus_thread_object.cpp
  src/dbus/server/dbus_thread_object.hpp
  src/dbus/server/introspect.xml
  src/ncp/ncp_openthread.cpp
  src/proto/feature_flag.proto
  third_party/openthread/CMakeLists.txt
Labels: comp: dns

#1783 [mdns] keep avahi service resolver until instance is removed
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_avahi.hpp
Labels: mdns, Avahi

#1776 [dbus] fix null attach handler issue
  src/utils/thread_helper.cpp
  src/utils/thread_helper.hpp
Labels: bug, P3, comp: dbus

#1807 [docs] link the Border Router codelab in README
  README.md
Labels: comp: docs
