Repository openthread/ot-br-posix, pull requests merged in 2025-02, with the labels that each got.

#2691 [tests] remove stale code in test bootstrap script
  tests/scripts/bootstrap.sh
Labels: P4, cleanup, github_actions

#2690 [dbus] add Join and SetThreadEnabled method to Dbus RCP
  src/dbus/common/constants.hpp
  src/dbus/server/dbus_thread_object_rcp.cpp
  src/dbus/server/dbus_thread_object_rcp.hpp
Labels: enhancement, P3, comp: dbus

#2698 [docker] use `arm64` runner instead of `qemu`
  .github/workflows/docker.yml
  etc/docker/Dockerfile
Labels: platform: docker, github_actions

#2697 [task-runner] only perform read when FD is set
  src/common/task_runner.cpp
Labels: enhancement, P3

#2720 [backbone-router] make header guard style consistent
  src/backbone_router/dua_routing_manager.hpp
  src/backbone_router/nd_proxy.hpp
Labels: enhancement, P4

#2721 [mdns] check if the `Publisher` is ready in `Register()` and `Unregister()` for mDNSResponder
  src/mdns/mdns_mdnssd.cpp
Labels: mdns, mDNSResponder

#2710 [mdns-publisher] move link-local address filtering to DiscoveryProxy
  src/mdns/mdns_avahi.cpp
  src/mdns/mdns_mdnssd.cpp
  src/sdp_proxy/discovery_proxy.cpp
  src/sdp_proxy/discovery_proxy.hpp
Labels: enhancement, P4

#2676 [posix] add POSIX CLI daemon module
  src/host/posix/CMakeLists.txt
  src/host/posix/cli_daemon.cpp
  src/host/posix/cli_daemon.hpp
  tests/gtest/CMakeLists.txt
  tests/gtest/test_cli_daemon.cpp
Labels: P2, comp: ncp, platform: posix

#2701 [pd] deprecate old prefixes in radvd configuration on DHCPv6 PD change
  script/reference-device/dhcpcd.enter-hook
  script/reference-device/dhcpcd.exit-hook
Labels: comp: pd
